### ISSUE TITLE
Loading time increased by 3s with PHP 8.1.11?

### ISSUE THREAD

**Issue by iwasherefirst2** [codeat3/blade-simple-icons#63]
Hi,

when I install this package with a fresh Laravel framework (v.9.3.8) with PHP 8.1.11 this package slows down the request time from 0.2s to 3.2s.

Do you have an idea why this could happen?

**Comment by swapnilsarwe** [comment]
Since running `php artisan icons:cache` has been our default way, we never thought of updating `README.md` regarding it. But mentioning it in our README.md is a good idea. Thanks for the PR.

**Comment by iwasherefirst2** [comment]
Yes I actually found out that you mentioned it at https://github.com/codeat3/blade-simple-icons#blade-icons
